main_prompt_path: prompts/main_prompt.txt
rag_summarize_prompt_path: prompts/rag_summarize.txt
query_rewrite_prompt_path: prompts/query_rewrite.txt
rerank_prompt_path: prompts/rerank.txt
intent_router_prompt_path: prompts/intent_router.txt
transform_query_prompt_path: prompts/transform_query.txt
smalltalk_answer_prompt_path: prompts/smalltalk_answer.txt
